# Change these first
owner: chitraganapathy # Your GitHub organization or username, where this repository lives
repo: chitrasfoodbook-uptime # The name of this repository

sites:
  - name: cfb
    url: https://www.chitrasfoodbook.com
  - name: cfb-staging
    url: https://staging.chitrasfoodbook.com
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /chitrasfoodbook-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Uptime** is the uptime monitor and status page for chitrasfoodbook, powered entirely by GitHub."
  introMessage: Status page which uses **real-time** data from chitrasfoodbook.com and staging.chitrasfoodbook.cim using just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
